import Head from 'next/head';
import Image from 'next/image';

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>STAR WARS</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>{children}</main>
      <footer class='text-center'>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          <div class='flex justify-center space-x-4'>
            <span>Built by Jessica Martínez</span>
            <Image src='/github.png' alt='gitHub logo' width={25} height={3} />
            <Image
              src='/linkedin.png'
              alt='LinkedIn Logo'
              width={25}
              height={3}
            />
          </div>
        </a>
      </footer>
    </>
  );
};

export default Layout;
