import Head from 'next/head';
import Image from 'next/image';
import Navbar from './Navbar';

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>STAR WARS</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <main>{children}</main>
      <footer className='bg-slate-200 h-[5rem] text-center items-center py-6 px-10 z-10 fixed bottom-0 w-full'>
        <div className='flex justify-between space-x-4'>
          <span>Built by Jessica Martínez</span>
          <div className='flex justify-between'>
            <a
              className='w-10 h-10 mx-2'
              href='https://github.com/Jessaleem'
              target='_blank'
              rel='noopener noreferrer'
            >
              <Image
                src='/github.png'
                alt='gitHub logo'
                width={25}
                height={25}
              />
            </a>
            <a
              className='w-10 h-10 mx-2'
              href='https://www.linkedin.com/in/jessaleem/'
              target='_blank'
              rel='noopener noreferrer'
            >
              <Image
                src='/linkedin.png'
                alt='LinkedIn Logo'
                width={25}
                height={25}
              />
            </a>
          </div>
        </div>
      </footer>
    </>
  );
};

export default Layout;
